In [2]:
import requests 
import pandas as pd
import json

In [20]:
endpoint= "https://api.acleddata.com/acled/read/?key=GsdDQ4dqB12pDDOdS1Z7&email=forogh.akbari.4726@student.uu.se"

In [39]:
# Set API endpoint and parameters
endpoint= "https://api.acleddata.com/acled/read/?key=GsdDQ4dqB12pDDOdS1Z7&email=forogh.akbari.4726@student.uu.se"
params = {
    'event_type': 'Battles',
    'start_date': '2014-01-01',
    'end_date': '2023-01-01',
    'limit': 1000, # Default limit is 500 rows
    'page': 1 # Start with the first page
}

# Send request and retrieve data
data = []
while True:
    response = requests.get(endpoint, params=params)
    page_data = response.json()['data']
    if not page_data:
        break
    data.extend(page_data)
    params['page'] += 1
    # Use limit query name to change number of rows per page
    # For example, params['limit'] = 1000 for export_type='monadic'
    # Setting limit as 0 will return all relevant data, but may cause a timeout error

# Convert data to DataFrame
df = pd.DataFrame(data)

In [55]:
list1=(list(df['country']))
set(list1)

{'Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Costa Rica',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Ethiopia',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guadeloupe',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Ivory Coast',
 'Jamaica',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Mauritania',
 'Mayotte',
 'Mexico',
 'Moldova',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Puerto Rico',
 'Republic of Congo',
 'Russia',
 'Rwanda',
 'Saint Vincent and the Grenadines',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Kingdom',
 'United States',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'eSwatini'}

In [47]:
list(df.columns)

['data_id',
 'iso',
 'event_id_cnty',
 'event_id_no_cnty',
 'event_date',
 'year',
 'time_precision',
 'event_type',
 'sub_event_type',
 'actor1',
 'assoc_actor_1',
 'inter1',
 'actor2',
 'assoc_actor_2',
 'inter2',
 'interaction',
 'region',
 'country',
 'admin1',
 'admin2',
 'admin3',
 'location',
 'latitude',
 'longitude',
 'geo_precision',
 'source',
 'source_scale',
 'notes',
 'fatalities',
 'timestamp',
 'iso3']

In [57]:
df.to_csv('/Users/foroghakbari/Documents/GitHub/Data-Viz-ACLED-updates/acled_battle_data.csv', sep='\t')

In [40]:
acled = pd.read_csv('/Users/foroghakbari/Documents/GitHub/Data-Viz-ACLED-updates/acled_battle_data.csv',sep='\t')

In [41]:
acled.drop('Unnamed: 0', axis=1, inplace=True)

In [58]:
acled

,data_id,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
0,9835079,180,DRC28683,28683,2023-02-10,2023,1,Battles,Armed clash,Military Forces of the Democratic Republic of ...,...,Kanyatsi,0.4367,29.3247,1,Mediacongo.net,National,"On 10 February 2023, FARDC clashed with ADF in...",0,1676309784,COD
1,9835080,180,DRC28684,28684,2023-02-10,2023,1,Battles,Armed clash,Military Forces of the Democratic Republic of ...,...,Karenga,-1.4724,29.0655,1,SOS Medias,New media,"On 10 February 2023, FARDC clashed with M23 in...",0,1676309784,COD
2,9835202,231,ETH9751,9751,2023-02-10,2023,1,Battles,Armed clash,OLF: Oromo Liberation Front (Shane Splinter Fa...,...,Chobi,9.3333,37.9500,2,Oromiya Media Network,International,"On 10 February 2023, OLF-Shane clashed with go...",8,1676309784,ETH
3,9835435,706,SOM39510,39510,2023-02-10,2023,1,Battles,Armed clash,Military Forces of Somaliland (2010-),...,Laascaanood,8.4774,47.3597,1,Caasimada; Radio Risala,National,"On 10 February 2023, Somalialand security forc...",6,1676309785,SOM
4,9835438,706,SOM39513,39513,2023-02-10,2023,1,Battles,Government regains territory,Military Forces of Somalia (2022-),...,Camaara,5.1143,47.9303,2,Caasimada; Calamada; Hiiraan (Somalia),National,"On 10 February 2023, government security force...",127,1676309785,SOM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301309,9631701,800,UGA1,1,1997-01-01,1997,3,Battles,Armed clash,Military Forces of Uganda (1986-),...,Gulu,2.7667,32.3056,3,Africa Research Bulletin,Other,Ugandan army battled with LRA rebels - 4 rebel...,4,1667943770,UGA
301310,9631702,800,UGA2,2,1997-01-01,1997,3,Battles,Armed clash,Military Forces of Uganda (1986-),...,Mityana,0.4015,32.0452,3,Africa Research Bulletin,Other,Over 20 rebel groups believed to belong to Dun...,5,1667943770,UGA
301311,9695770,694,SIE2,2,1997-01-01,1997,3,Battles,Government regains territory,Military Forces of Sierra Leone (1996-1997),...,Mandu,8.4642,-10.9332,2,No Peace Without Justice; SL-LED,Local partner-New media,"Around 1 January 1997 (month of), Military For...",0,1670286851,SLE
301312,9695771,694,SIE3,3,1997-01-01,1997,3,Battles,Armed clash,Kamajor Militia,...,Selenga,8.1221,-11.7047,2,No Peace Without Justice; SL-LED,Local partner-New media,"Around 1 January 1997 (month of), Kamajor Mili...",0,1670286851,SLE
301313,9695773,694,SIE7,7,1997-01-01,1997,3,Battles,Armed clash,Kamajor Militia,...,Fakunya,8.2310,-12.3380,2,SL-LED; No Peace Without Justice,Local partner-New media,"Around 1 January 1997 (month of), Kamajor Mili...",0,1670286851,SLE

In [43]:
set(acled['country'])

{'Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Costa Rica',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Ethiopia',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guadeloupe',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Ivory Coast',
 'Jamaica',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Mali',
 'Mauritania',
 'Mayotte',
 'Mexico',
 'Moldova',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Macedonia',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Puerto Rico',
 'Republic of Congo',
 'Russia',
 'Rwanda',
 'Saint Vincent and the Grenadines',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Sweden',
 'Switzerland',
 'Syria',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Kingdom',
 'United States',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe',
 'eSwatini'}

In [42]:
set(acled.columns.tolist())

{'actor1',
 'actor2',
 'admin1',
 'admin2',
 'admin3',
 'assoc_actor_1',
 'assoc_actor_2',
 'country',
 'data_id',
 'event_date',
 'event_id_cnty',
 'event_id_no_cnty',
 'event_type',
 'fatalities',
 'geo_precision',
 'inter1',
 'inter2',
 'interaction',
 'iso',
 'iso3',
 'latitude',
 'location',
 'longitude',
 'notes',
 'region',
 'source',
 'source_scale',
 'sub_event_type',
 'time_precision',
 'timestamp',
 'year'}

In [15]:
acled.columns.tolist()

['data_id',
 'iso',
 'event_id_cnty',
 'event_id_no_cnty',
 'event_date',
 'year',
 'time_precision',
 'event_type',
 'sub_event_type',
 'actor1',
 'assoc_actor_1',
 'inter1',
 'actor2',
 'assoc_actor_2',
 'inter2',
 'interaction',
 'region',
 'country',
 'admin1',
 'admin2',
 'admin3',
 'location',
 'latitude',
 'longitude',
 'geo_precision',
 'source',
 'source_scale',
 'notes',
 'fatalities',
 'timestamp',
 'iso3']

In [33]:
acled=acled.reset_index()

In [54]:
acled['event_date'] = pd.to_datetime(acled['event_date'])

result = acled.groupby([pd.Grouper(key='event_date', freq='M'), 'data_id','country',
                        
                        'iso', 'event_id_cnty', 'event_id_no_cnty',
                        'year', 'time_precision', 'event_type',
                        'sub_event_type', 'actor1', 'assoc_actor_1',
                        'inter1', 'actor2', 'assoc_actor_2', 'inter2',
                        'interaction', 'region', 'country', 'admin1',
                        'admin2', 'admin3', 'location', 'latitude',
                        'longitude', 'geo_precision', 'source',
                        'source_scale', 'notes', 'timestamp', 'iso3']
                      ).agg({'fatalities': 'sum'})

In [57]:
result.reset_index()

ValueError: cannot insert country, already exists

In [52]:
set(result['country'])

{'Bangladesh',
 'Belgium',
 'Bolivia',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'China',
 'Comoros',
 'Democratic Republic of Congo',
 'Ethiopia',
 'Guinea',
 'Haiti',
 'Honduras',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Ivory Coast',
 'Kenya',
 'Madagascar',
 'Mali',
 'Mauritania',
 'Morocco',
 'Myanmar',
 'Niger',
 'Pakistan',
 'Peru',
 'Philippines',
 'Sierra Leone',
 'South Africa',
 'South Sudan',
 'Sri Lanka',
 'Syria',
 'Tanzania',
 'Thailand',
 'Uganda',
 'Ukraine'}

In [38]:
result.to_csv('/Users/foroghakbari/Documents/GitHub/Data-Viz-ACLED-updates/acled_battle_data_month.csv', sep='\t')

In [97]:
df = pd.DataFrame({
    'date': pd.date_range(start='2021-01-01', end='2021-12-31', freq='W'),
    'value': np.random.randint(1, 100, size=52)
})

# convert the 'date' column to the index
df.set_index('date', inplace=True)

# resample the DataFrame from weekly to monthly frequency and sum the values
df_monthly = df.resample('M').sum()

# reset the index to a column and rename it to 'date'
df_monthly = df_monthly.reset_index().rename(columns={'index': 'date'})

# print the monthly aggregated DataFrame
print(df_monthly)

         date  value
0  2021-01-31    229
1  2021-02-28    186
2  2021-03-31    187
3  2021-04-30    195
4  2021-05-31    374
5  2021-06-30    236
6  2021-07-31    274
7  2021-08-31    235
8  2021-09-30    254
9  2021-10-31    254
10 2021-11-30    209
11 2021-12-31    258

In [26]:
df = pd.DataFrame(all_data)

print(df.head())

             0
0       status
1      success
2  last_update
3        count
4     messages

In [25]:
data = response.json()
all_data.extend(data)

if len(data) < params['limit']:
            # All data has been retrieved
            break
        else:
            # Get the next page
            params['page'] += 1
    else:
        print(f'Request failed with status code {response.status_code}')
        break


df = pd.DataFrame(all_data)

print(df.head())

             0
0       status
1      success
2  last_update
3        count
4     messages